# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/OpenHardware/UserProject/PuBeTrigger5/output/PuBeTrigger5/PuBeTrigger5.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_auto_pc_1/ZynqDesign_auto_pc_1.xci
# IP: The module: 'ZynqDesign_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OpenHardware/UserProject/PuBeTrigger5/output/PuBeTrigger5/PuBeTrigger5.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_auto_pc_1/ZynqDesign_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/OpenHardware/UserProject/PuBeTrigger5/output/PuBeTrigger5/PuBeTrigger5.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_auto_pc_1/ZynqDesign_auto_pc_1.xci
# IP: The module: 'ZynqDesign_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/OpenHardware/UserProject/PuBeTrigger5/output/PuBeTrigger5/PuBeTrigger5.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_auto_pc_1/ZynqDesign_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqDesign_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
