# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/HDL/SCIDK_constraints.xdc

# IP: ip/clk_125MHZ/clk_125MHZ.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_125MHZ || ORIG_REF_NAME==clk_125MHZ} -quiet] -quiet

# IP: ip/FTDI_FIFOs/FTDI_FIFOs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FTDI_FIFOs || ORIG_REF_NAME==FTDI_FIFOs} -quiet] -quiet

# IP: ip/main_clk_gen/main_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_clk_gen || ORIG_REF_NAME==main_clk_gen} -quiet] -quiet
